apiVersion: v1
kind: Service
metadata:
  name: proxy-server
  labels:
    app: proxy-server
spec:
  selector:
    app: proxy-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
